MATERIALS = [
    {
        "id": "hybrid_gi_gfrp",
        "name": "Galvanized steel frame + GFRP sandwich panels",
        "category": "Hybrid composite",
        "cost": 3,
        "weight_saving_pct": 28,
        "strength": 4,
        "corrosion": 4,
        "abrasion": 3,
        "thermal": 3,
        "fire": 3,
        "repairability": 4,
        "availability_india": 5,
        "manufacturing_fit": 5,
        "summary": "Best practical starting point for many Indian truck carriers: keep the main load path metallic, replace large welded steel sheets with modular composite panels.",
        "manufacturing": "Use a jig-welded or bolted galvanized frame, GFRP/PU or GFRP/PP sandwich panels, structural adhesive, rivets/bolts, edge sealing, and replaceable corner/wear plates.",
        "watchouts": "Validate adhesive/rivet spacing, panel edge sealing, fire rating, and impact zones. Use steel/aluminium hard points where cargo is strapped or fork-loaded.",
    },
    {
        "id": "ahss_galvanized",
        "name": "AHSS / galvanized steel modular panels",
        "category": "Improved steel",
        "cost": 2,
        "weight_saving_pct": 12,
        "strength": 5,
        "corrosion": 3,
        "abrasion": 4,
        "thermal": 4,
        "fire": 5,
        "repairability": 5,
        "availability_india": 5,
        "manufacturing_fit": 4,
        "summary": "Lowest adoption risk. It improves current steel fabrication using thinner high-strength sections, zinc protection, modular panels, and better coatings.",
        "manufacturing": "Replace large sheet welding with laser/plasma-cut modules, roll-formed ribs, plug welding/bolting, hot-dip galvanizing or zinc-rich primer, epoxy primer, and PU topcoat.",
        "watchouts": "Weight saving is modest versus composites. Corrosion protection fails quickly if edges, weld burns, and drilled holes are not sealed.",
    },
    {
        "id": "al_5052_5083",
        "name": "Aluminium 5052/5083 panels + steel subframe",
        "category": "Aluminium hybrid",
        "cost": 4,
        "weight_saving_pct": 35,
        "strength": 3,
        "corrosion": 4,
        "abrasion": 2,
        "thermal": 4,
        "fire": 5,
        "repairability": 3,
        "availability_india": 4,
        "manufacturing_fit": 3,
        "summary": "Strong option for high-mileage logistics, refrigerated bodies, and coastal use when budget allows better joining and galvanic isolation.",
        "manufacturing": "Use aluminium panels/extrusions with bolted/riveted joints, isolate steel-aluminium interfaces, add stainless/nylon washers, apply epoxy barrier coatings, and avoid direct galvanic couples.",
        "watchouts": "Needs skilled joining, isolation from steel, and dent/abrasion protection. Material cost volatility can hurt economics.",
    },
    {
        "id": "gfrp_pultruded",
        "name": "Pultruded GFRP profiles + FRP skins",
        "category": "Composite",
        "cost": 4,
        "weight_saving_pct": 40,
        "strength": 3,
        "corrosion": 5,
        "abrasion": 2,
        "thermal": 3,
        "fire": 2,
        "repairability": 3,
        "availability_india": 3,
        "manufacturing_fit": 3,
        "summary": "Useful for corrosion-heavy carriers and covers, but pure composite primary load paths require engineering validation and production discipline.",
        "manufacturing": "Use pultruded beams, FRP sandwich panels, bonded/riveted joints, UV gelcoat, sealed edges, and metallic inserts at load points.",
        "watchouts": "Poor design can crack at point loads. Fire/smoke requirements, UV aging, and repair training must be handled up front.",
    },
    {
        "id": "al_honeycomb",
        "name": "Aluminium honeycomb sandwich panels",
        "category": "Sandwich panel",
        "cost": 5,
        "weight_saving_pct": 45,
        "strength": 4,
        "corrosion": 4,
        "abrasion": 2,
        "thermal": 4,
        "fire": 5,
        "repairability": 2,
        "availability_india": 3,
        "manufacturing_fit": 2,
        "summary": "Excellent lightweight panel where stiffness matters, but usually too costly for rough-duty commodity carriers.",
        "manufacturing": "Use bonded sandwich panels in doors, roofs, side walls, and floors with perimeter frames and crush-resistant inserts.",
        "watchouts": "Edge water ingress and local crushing are common failure modes. Needs controlled bonding and careful repair process.",
    },
    {
        "id": "cfrp_sandwich",
        "name": "CFRP sandwich panels",
        "category": "Premium composite",
        "cost": 6,
        "weight_saving_pct": 55,
        "strength": 5,
        "corrosion": 5,
        "abrasion": 2,
        "thermal": 2,
        "fire": 2,
        "repairability": 1,
        "availability_india": 2,
        "manufacturing_fit": 1,
        "summary": "Maximum weight saving for premium applications, but very high cost and limited repairability make it unsuitable for most Indian truck carriers.",
        "manufacturing": "Requires autoclave or vacuum infusion, prepreg layup, CNC trimming, bonded joints, and strict quality control throughout.",
        "watchouts": "Extremely high material and tooling cost, brittle failure mode, very difficult to repair in the field, and limited local supply chain in India.",
    },
        {
        "id": "ss304_lined",
        "name": "SS304 contact surfaces + hybrid frame",
        "category": "Hygienic / chemical",
        "cost": 5,
        "weight_saving_pct": 8,
        "strength": 4,
        "corrosion": 5,
        "abrasion": 4,
        "thermal": 5,
        "fire": 5,
        "repairability": 4,
        "availability_india": 4,
        "manufacturing_fit": 3,
        "summary": "Use only where hygiene, chemicals, or washdown duty justify the cost and weight.",
        "manufacturing": "Use stainless liners/contact areas with a galvanized or aluminium structural frame, TIG/MIG welding where needed, and sealed joints.",
        "watchouts": "Too expensive and heavy for general logistics. Chloride stress and chemical compatibility still need checking.",
    },
    {
        "id": "natural_fiber_pp",
        "name": "Jute/coir/sisal reinforced PP interior panels",
        "category": "Bio-composite",
        "cost": 2,
        "weight_saving_pct": 22,
        "strength": 2,
        "corrosion": 4,
        "abrasion": 1,
        "thermal": 2,
        "fire": 1,
        "repairability": 3,
        "availability_india": 4,
        "manufacturing_fit": 3,
        "summary": "Good for non-structural interior liners and trim, not for primary carrier structure or high-abuse floors.",
        "manufacturing": "Compression mold panels with moisture barrier skins; use as inner lining, partitions, or covers away from direct abrasion.",
        "watchouts": "Moisture uptake, fire behavior, UV aging, and low point-load strength limit its use.",
    },
]


SECTOR_PROFILES = {
    "General logistics": {"abrasion": 2, "hygiene": 1, "impact": 3, "fire": 2},
    "E-commerce / parcel": {"abrasion": 1, "hygiene": 1, "impact": 2, "fire": 2},
    "Agriculture": {"abrasion": 3, "hygiene": 2, "impact": 3, "fire": 2},
    "Construction material": {"abrasion": 5, "hygiene": 1, "impact": 5, "fire": 2},
    "Mining / quarry": {"abrasion": 5, "hygiene": 1, "impact": 5, "fire": 3},
    "Cold chain / food": {"abrasion": 2, "hygiene": 5, "impact": 2, "fire": 3},
    "Chemicals / coastal": {"abrasion": 2, "hygiene": 4, "impact": 3, "fire": 4},
}


CLIMATE_PROFILES = {
    "Coastal humid / saline": {"corrosion": 5, "thermal": 3, "uv": 4, "moisture": 5},
    "Hot dry / dusty": {"corrosion": 2, "thermal": 5, "uv": 5, "moisture": 1},
    "Monsoon heavy inland": {"corrosion": 4, "thermal": 3, "uv": 3, "moisture": 5},
    "Industrial / polluted": {"corrosion": 4, "thermal": 3, "uv": 3, "moisture": 3},
    "Mixed pan-India": {"corrosion": 4, "thermal": 4, "uv": 4, "moisture": 4},
}
